### ISSUE TITLE
can't setup wallet

### ISSUE THREAD

**Issue by dchmelik** [greymass/anchor#1026]
When I go to setup it says 'existing account,' but I don't have one: I'm new to EOS... how does one get started without yet having an account or knowing what one is?

**Comment by aaroncox** [comment]
You've stumbled into one of the most confusing parts of the EOS (and EOSIO) user experience. Accounts are a blockchain level object that houses you and your associated keys, and they have a cost associated with their creation. Currently to get an account on the blockchain, you have to go through some sort of 3rd party to have one created (a service, another person, a smart contract, etc).

Because of this - we don't yet have account creation for new users in Anchor, but it's something we've been working on for the last few months and will be releasing in the not too distant future. It's been hard to get right while keeping both easy and secure.

The easiest way today would be to:

1. Generate your key pairs, you'll need either 1 or 2 pairs (public/private pairs). You can do this by going into the Tools section under Manage Keys, and there's a button near the top to generate them locally. **Save these someplace safe**, external of the wallet, as a backup. These keys will control your account. There's options to copy them to your clipboard so you can back them up to your preferred location. Also click "Save to Wallet" in Anchor to save them within your wallet app.
2. Once you have your key pairs, you'll use the PUBLIC keys (the ones that start with `EOS`, NOT the ones that start with the number `5`) to have a 3rd party create your account. There are a bunch of different services that will create accounts for new EOS users, many have a cost associated with them to cover the services cost in creating an account. By searching the internet for "eos create account" you'll likely stumble on a few of them. I hesitate to recommend any simply because I am not affiliated with any live services at the moment.
3. You'll use your PUBLIC keys in these services when asked, go through their processes, and they should create your account.
4. Once the account is created, in Anchor, you'll go into the setup process and click the "Automatically Detect" option. This will perform a lookup of the keys you saved in Step 1 against the API servers (using the public keys) to automatically find your account. It may take a minute or two for them to appear, depending on how fast or slow the account creation service is. Check the checkbox next to the account in question, hit import, and you should be good to go!

In the future if you ever setup a new wallet, you'll be able to take the private keys you saved in step 1 and just import them into Anchor (or any other wallet). The wallet will find your account and let you get setup again. 

This process is complicated and honestly sucks - which is why we're working on solutions to make it easier. There are other wallets out there which already make it easier if you want to give them a shot. One word of warning though, is that a lot of the wallets that will do it for you for free retain control of the account, and thus ultimately your funds, and require a purchase after the fact to take full control of your account.
