### ISSUE TITLE
AVAILABLE EOS not displaying on Anchor Wallet

### ISSUE THREAD

**Issue by emmaivybriar** [greymass/anchor#1036]
My wallet only shows STAKED EOS, not the AVAILABLE EOS. Can you advise? Thanks.

**Comment by aaroncox** [comment]
It's possible the request for that balance failed on initial load. If you give it a bit of time, it should retry. 

One way to force a retry would be to go into Resources, and click the "Refresh" button in the upper right. We should probably add the optional to manually force a refresh on balance from the main screen as well.

**Comment by emmaivybriar** [comment]
Thanks for the fast response. EOS balance is still not showing. I can see the available balance through the EOSX portal but not directly on the Anchor Wallet. All it shows is the staked balance.

**Comment by aaroncox** [comment]
Interesting - wonder if there's a bug with certain accounts, since all of my test cases seem to be loading alright. 

Mind sharing the account name? If you don't want to post it on Github but are willing to share, feel free to email it over to team@greymass.com and I can receive it there. Knowing the account name and it's current state may help in tracking down why the balance won't load.

**Comment by emmaivybriar** [comment]
Sure, no problem. I just emailed it to you, along with screen shots. Appreciate the help!

**Comment by aaroncox** [comment]
Nothing looks out of place, and the account data seems normal. Few questions and comments:

1. What version of Anchor are you running? If it's an older version, an upgrade might help (we're on 1.1.12 now). 
2. Which API are you connected to? You can find this by clicking the EOS icon in the upper left, and then going into "Manage Blockchains". Click the small gear icon in the EOS box to open the settings and one of those fields is the API Node. You can try changing that to either `https://eos.greymass.com` or `https://eos.eosn.io` to see if that resolves the issue. 
3. Was this account imported long ago, into either an earlier version of Anchor or even eos-voter? It's possible something in the configuration has gone haywire through the multiple upgrades - and starting over and resetting the wallet might resolve the problem. I can give instructions on how to do that if all else fails. 

While we're figuring this out as well, you can always use Anchor to login to a web wallet like bloks.io, eosauthority.com, or eosx.io. All of those web interfaces work with Anchor and would allow you to perform transfers or any other operation if this bug is blocking you from doing what you need to do.

**Comment by emmaivybriar** [comment]
Thanks I just emailed you. I am using the latest version. I switched API but it did not change anything. 
I originally used the EOS voter wallet. So maybe we just need to reset as you suggest?
Let me know how I can do that. Thank you Aaron.

**Comment by aaroncox** [comment]
Alright good to know, this probably is an issue that we just haven't been able to track down and involves how the upgrades between eos-voter and Anchor have gone. I'm hopeful a reset will fix it.

To do a reset of the wallet, and to start fresh, the first thing I'd recommend is creating a fresh backup. This can be done using the Home screen of the app and will save a JSON file somewhere on your computer. If anything goes wrong during this process, you'll be able to restore Anchor using that file to the state it was in before you started this process.

Before you reset, you'll need to export the private keys themselves to use when you're setting up the fresh wallet. This part can be risky if your computer is compromised, so make sure you're doing this on a secure computer. Exporting each private key can be done through the "Manage Wallets" interface in the account dropdown (upper left). You'll need the wallet unlocked, and then use the "View Wallet" option:

![image](https://user-images.githubusercontent.com/677686/107255208-0f103300-6a06-11eb-9fc6-cca2bb17ad16.png)

Towards the bottom of the screen that pops up, there's a private key field, with a checkbox below it. Check the checkbox to reveal the private key for that account. It's a long string of letters and numbers that starts with a 5. Put each of these keys in a text file or something, you'll need them after the reset during the import process.

Once you have a backup of Anchor created, and all of your private keys exported, the next thing you'll want to do is go into Tools. In the upper right corner of this interface, there's a "Reset App" button. Clicking this button will wipe all data (keys, actions, tracked tokens, etc) and bring Anchor into the state it was in when it was first installed. Once you're ready, go ahead and hit that. 

Now you're in a freshly installed state. You'll set up the wallet like a new user would:

1. Hit Setup Wallet and select a blockchain.
2. Establish a password for Anchor (it can be your old one or a new one). 
3. Import each account, using the "Import via Private Key" option. 
4. Select the account(s) to import based on the key. 

Repeat Step 3 for as many accounts as you need to import. 

At this point you should have a brand new wallet setup, utilizing your same private keys, and my hopes is that any related issues from eos-voter that transferred over with your backup are now resolved. 👍

**Comment by emmaivybriar** [comment]
Thank you Aaron. I'm trying to do the initial backup but the JSON file is only 24kb and doesn't seem to be saving anything. What am I doing wrong?

**Comment by aaroncox** [comment]
The backups themselves aren't that big. If you still have eos-voter installed as well, that can serve as a backup too since both eos-voter and Anchor are completely independent apps.

**Comment by emmaivybriar** [comment]
Hey Aaron, I just reset and it works perfectly now! One other question, can I use the Anchor wallet with Ledger Nano S?
