### ISSUE TITLE
WAX showing but seems inaccessible

### ISSUE THREAD

**Issue by Another-Joe** [greymass/anchor#1095]
As long as I can remember, I've been able to see my WAX tokens but not access them. I just figured it was a glitch that would clear up with an update, then I forget for awhile, then I try again and the same thing. What's going on?

**Comment by aaroncox** [comment]
Might be a UI bug. We are up to version 1.2.2 now, I'm curious to know if that resolves the issue. 

I'd probably also recommend looking at the account on wax.bloks.io and see if there's any information you can glean. 

If 1.2.2 still doesn't work, knowing the account name itself would likely help because we'd be able to setup a Watch Wallet for it and see the exact same interface you would see (anyone can setup a watch wallet for any account, feel free to try). If 1.2.2 doesn't resolve it and you don't mind sharing that account name, feel free to email it to team@greymass.com and we can take a look.

**Comment by Another-Joe** [comment]
Thanks Aaron,
I am updated to 1.2.1. I took the snap a bit ago and just didn't get to sharing until today.
It still shows the same in 1.2.1. But on the blockchain it shows no wax at all, just Karma
This is a genesis acct, in case that helps. Do you know if there are WAX tokens somehow locked or something?

**Comment by aaroncox** [comment]
That's very weird, I haven't run into this before. 

The "Total" column is a combination of staked, liquid, refunding, delegated and REX (where it exists), so there's a number of places it could be coming from. 

Without digging into the account itself and looking I'm not sure what it could be though.

**Comment by Another-Joe** [comment]
Emailed

Thanks Aaron
