### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by bayzora** [greymass/anchor#1130]
![image](https://user-images.githubusercontent.com/85624228/121355213-a5ddf500-c8fd-11eb-946c-6d0fd5d65610.png)

I get this error when trying to log on from the wax web screen. please advise.

**Comment by aaroncox** [comment]
Which version are you using? We have been working to resolve this on certain versions, so if you're on an older version this may be resolved.

**Comment by bayzora** [comment]
This is the newest version 1.2.4. I can open the window but the interaction between the browser and the app is not linking. Not sure why. I even went as far as installing a fresh version over, but that didn't seem to do anything. So I am wondering if there is something in the cache that is preventing the connection.

**Comment by aaroncox** [comment]
This error happens when Anchor is unable to connect to a relay server, which is used to relay requests from dapps to your device. 

Give this page a try and see if you're able to connect to the relay servers at all:

https://greymass.github.io/anchor-link-diagnostics/

I'm wondering if either something on your computer, or something on your network, is preventing you from reaching those servers and allowing the connection between you and our servers.

**Comment by ngotrung42** [comment]
I met such error with version 1.2.4.
When checking, the DNS connection error.
How do I fix it? I uninstalled it again but it didn't work
![Uploading Screenshot_37.png…]()

**Comment by CouchFrancois** [comment]
Getting the same error in 1.2.5

Ran the diagnostics without an issue.  It doesn't happen immediately, but after maybe 5 minutes in the background
 
![Screenshot 2021-06-26 085955](https://user-images.githubusercontent.com/1000466/123515423-eeffaa00-d65c-11eb-9b4d-3932887700d1.png)

**Comment by aaroncox** [comment]
We pushed an update out today that we hope resolves this (1.2.6). Feel free to update (Help menu -> Check for Updates), but want to continuing monitoring if this is resolved. 

I'm going to close out this issue, but feel free to continue the discussion here: 

https://github.com/greymass/anchor/issues/1139

**Comment by CouchFrancois** [comment]
This issue is still happening in 1.2.6
