### ISSUE TITLE
Open sign window where it was the last time and don't  move it into the center

### ISSUE THREAD

**Issue by Mardaklysm** [greymass/anchor#1146]
Somehow the behavior for where the sign window opens keeps changing from version to version.

Please make it so that the sign window opens where u had it the last time and not in the middle of the stream. This makes it very hard to use anchor for time critical oeprations like claiming drops on wax.

For example when the sign window is still open from another transaction and I move it and want to sign another transaction it jumps into the middle. This is very annoying when you have to sign like 100 transaction in a row and need to see whats happening in the middle of the screen.

**Comment by aaroncox** [comment]
The "remember position" feature of that window has been removed recently because it was causing a lot of headaches for some users. Like I mentioned in the other issue about sizing, it had to do with changes in display configurations in some environments (like if you unplug a monitor from your laptop).

We can't have features that are convenient for some but break functionality for others. Until we find solutions and a way to make it work properly - the window unfortunately won't remember the last position and will appear in the center of the interface that triggered it.

**Comment by Mardaklysm** [comment]
> We can't have features that are convenient for some but break functionality for others.
This sounds like the perfect case for a setting?

Just an example, a week ago I had to do the same task over 400 times and it made me move away the sign window 400 times and press sign 400 times. I get that it doesn't matter if you make a single transaction every few days but if you make 100s a day it gets exhausting.

**Comment by aaroncox** [comment]
I think I found a happy middle ground for this. It'll now detect if the request is off screen (even by a bit) and if it does, it centers the window. If however it looks at the last position and determines its still a good position to show the window, it'll put it where you had it last.

**Comment by Mardaklysm** [comment]
> I think I found a happy middle ground for this. It'll now detect if the request is off screen (even by a bit) and if it does, it centers the window. If however it looks at the last position and determines its still a good position to show the window, it'll put it where you had it last.

Sounds great! :)
