### ISSUE TITLE
having issue with connecting wallet

### ISSUE THREAD

**Issue by VinitKhade** [greymass/anchor#1217]
vUnable to connect to the WAX blockchain please help to resolve issue
![greymass](https://user-images.githubusercontent.com/94619059/142422037-f709f4db-ef20-45a5-ba88-69663fb4586b.PNG)

**Comment by aaroncox** [comment]
From the looks of it, your computer is having a problem connecting to wax.greymss.com in time either due to latency or something blocking it. If the problem persists, you can hit the Edit Blockchain button and change which server you're connected to.

This page has a list of APIs you're able to use:

https://validate.eosnation.io/wax/reports/endpoints.html

If you have further issues with this, feel free to reach out to support@greymass.com and we can further assist.

**Comment by VinitKhade** [comment]
same happens on my andriod mobile app as well .

**Comment by VinitKhade** [comment]
![anchor error](https://user-images.githubusercontent.com/94619059/142491811-e76db4ce-442b-4a5f-915a-03ec0b3fe75e.PNG)
this is  the erro i am getting
