### ISSUE TITLE
Unable to import private keys

### ISSUE THREAD

**Issue by n3b** [greymass/anchor#1229]
The keys are correct, accounts do exists on blockchain and are discoverable via block explorer

<img width="673" src="https://user-images.githubusercontent.com/716480/147544213-80d701a4-31b5-4fdd-bdd5-72a5234a5667.png">

**Comment by kamil11-cloud** [comment]
Same problem. It automatically kog out. now I cant do any transaction because of the error in private keys

**Comment by inceptchain** [comment]
Same issue for me, shows up in block explorer, i updated to Anchor 1.3.2, I had tried using 1.2.1 both didnt work on importing private key. I generated the key using cleos.

**Comment by aaroncox** [comment]
Interesting, that was helpful. It shouldn't be using that API and that's why it was failing. 

One of our API servers wasn't responding to indicate the appropriate API was available. I just fixed that. Try restarting Anchor and see if it works now - it should detect the proper API call (v1/chain/get_accounts_by_authorizers) and use that to do imports now.

**Comment by djmbritt** [comment]
I was also experiencing this issue yesterday. It's working fine now.

**Comment by aaroncox** [comment]
Awesome - that must have been the issue then! If anyone is still experiencing this, please let me know. Going to close this out in the mean time - but feel free to reopen it or open a new issue.
