### ISSUE TITLE
Can you add complete Chinese?

### ISSUE THREAD

**Issue by hvwin** [greymass/anchor#1236]
If it is convenient, please let the content support Chinese!The current version chooses Chinese, and most of them will still be displayed in English! Many functions are needed!

**Comment by aaroncox** [comment]
Yeah - localization into other languages is something we need to take care of soon. We haven't had the capacity or people capable of doing full translations over the years, so it's fallen by the wayside. It's on our radar as an improvement!

Closing this issue out for now, since we're going to reduce this down to bug tracking, but know this is part of our plans.
