### ISSUE TITLE
Voting for a specific BP on FIO doesnt work

### ISSUE THREAD

**Issue by robrigo** [greymass/anchor#840]
On FIO, I can change BP votes from but when I try to vote for a specific BP with 0 votes I get an error.

bp FIO address is "fio@ttias"

<img width="843" alt="Screen Shot 2020-04-10 at 2 01 56 PM" src="https://user-images.githubusercontent.com/590263/79012763-15f3be00-7b35-11ea-881d-5f7972424041.png">

<img width="844" alt="Screen Shot 2020-04-10 at 2 02 41 PM" src="https://user-images.githubusercontent.com/590263/79012776-1b510880-7b35-11ea-98a5-5696763ff6be.png">

**Comment by aaroncox** [comment]
Interesting, this might actually be a FIO issue.

**Comment by aaroncox** [comment]
Oh, interesting. I think the reason this is happening is because they have the "disabled" signing key set on the BP:

```FIO1111111111111111111111111111111114T1Anm```

If you look in the eosio producers table as well, you'll see `is_active` is set to `0`. I'm not sure what they're doing or why they aren't registered properly yet, but the blockchain itself is preventing the vote and throwing an unrelated error.
