### ISSUE TITLE
New Scatter import beta

### ISSUE THREAD

**Issue by maxocoin** [greymass/anchor#910]
Just a few notes after trying the new Scatter import feature
  I tried to import a backup from Scatter 12.0.0  and it didn't get to the page that asks for the Scatter password, the spinner just kept running on the main screen.

 After, I tried with a Scatter 11 backup and it worked fine, but now, I can't unlock the wallet,
    * It didn't ask me to set a wallet password during the import process
    * It didn't accept the Scatter 11 password that I used when I imported the account
    * It didn't accept the Anchor password I had before I un-installed it for try the import

**Comment by aaroncox** [comment]
Thanks for this, seems like we haven't covered all the edge cases. 

Since this is a hard situation for us to reproduce (every backup is different), here's some questions if you don't mind:

- With the Scatter 12.0.0 backup, what sort of accounts were loaded in there? Were they accounts created by scatter using the mnemonic phrase, or were all the accounts individually imported by private keys?
- When you try to do the Scatter 12.0.0 backup, there may be some useful errors in the console of the developer tools. The view menu at the top has a Toggle Developer Tools option, which if you open before the import, may provide some relevant errors. 

We'll do a few more tests with 12 to see if we can spot anything too.

For 11, that's odd. It should just then use your Scatter password for Anchor going forward. The reset of the wallet wipes passwords, so it wouldn't remember your previous Anchor password. We'll have to take a look at this as well.

Fun times with experimental modes for everyone! 😂

**Comment by maxocoin** [comment]
> * When you try to do the Scatter 12.0.0 backup, there may be some useful errors in the console of the developer tools. The view menu at the top has a Toggle Developer Tools option, which if you open before the import, may provide some relevant errors.

I tried again and only  got this, 
[1591395595574.log](https://github.com/greymass/anchor/files/4738722/1591395595574.log) 
I created the backup in Scatter again, just in case it was corrupted, but it gave me the same error.

> For 11, that's odd. It should just then use your Scatter password for Anchor going forward. The reset of the wallet wipes passwords, so it wouldn't remember your previous Anchor password. We'll have to take a look at this as well.

Both imports (11 and 12) are for the same set of keys, the wallet has about 20 accounts, from nearly all the public EOSIO blockchains. 
Most have been added using a text private key, there are 3 ledger accounts and the rest have been create in Scatter 11 (individual private keys, without using a seed  phrase)

Cheers

**Comment by aaroncox** [comment]
Awesome, thanks for the details. We'll create a backup that will hopefully simulate what you're using and see if we can refine the process a bit more 👍

**Comment by aaroncox** [comment]
The 1.0.5 release is coming today which is going to address a number of issues during the Scatter import process, but I wouldn't bet on it resolving all of them. I'm going to bump this to the 1.0.6 milestone to keep it open as we continue to find more spots we can refine the process - but hopefully the original issue you reported will be resolved with 1.0.5.

**Comment by maxocoin** [comment]
I tried to import a few backups I had from scatter 12.0.0  and they all gave the same error and nothing was imported, 
[scatter_12.0.0-1592960458090.log](https://github.com/greymass/anchor/files/4831007/scatter_12.0.0-1592960458090.log)

The I tried an older Scatter 11.0.0 backup and even when it gave me the attached error, it was imported perfectly 
[scatter_11.0.0-1592960749493.log](https://github.com/greymass/anchor/files/4831011/scatter_11.0.0-1592960749493.log)

But I still can unlock the imported wallet. It asks me for a password and when I try the one I used for unlock the scatter backup it says "wrong password" and it never asked me to create a password for the imported wallet

**Comment by aaroncox** [comment]
Try giving 1.1.0 a shot with your backup - it *might* work now.

**Comment by maxocoin** [comment]
It works!!!!

But I would suggest some progress indicator ( something like the number of accounts imported so far)  
It took more than 15 minutes to import.
I thought it hung, but I didn't abort because I was busy with something else!!!

**Comment by aaroncox** [comment]
Well that's certainly a really long wait 😂 

We would like to get some sort of progress or UI wrapped around those processes - but haven't yet found the time. The time it takes to import varies wildly based on the hardware being used so some sort of progress indicator would be nice. 

I'm glad it works now though!
