### ISSUE TITLE
Please help, i cannot sent my EOS 

### ISSUE THREAD

**Issue by nielsti** [greymass/anchor#923]
Yesterday i sent around 10 EOS to my Bittrex account via the Anchor app.
Today i tried to sent the rest but somehow i don't succeed.
(There is nothing available to sent? see printscreen
![help](https://user-images.githubusercontent.com/67188998/85199442-f1b01c80-b2ef-11ea-95b9-2a489e0de260.jpg)
)

I am very new to this Anchor app and for a long time did not being busy with coins in general.
Hopefully someone here can help me out :-)

**Comment by aaroncox** [comment]
The tokens are currently "staked" (being used for resources), which is why they are unavailable. You'll have to unstake the tokens through the "Resources" section of the wallet. 

One thing to note - to do any operations on the network, you need tokens staked to cover the resource costs. Anchor does offer some free resources if you use the Fuel option in the upper right corner. You can enable it like so:

![https://i.imgur.com/OJz123n.gif](https://i.imgur.com/OJz123n.gif)

**Comment by nielsti** [comment]
Thank you kindly for this solution!
Is there any other and quicker way to unstake the tokens?
