### ISSUE TITLE
the "open anchor app" button is not working

### ISSUE THREAD

**Issue by fixedelineation** [greymass/anchor#949]
A User reported that they are unable to sign in to discussions.app via anchor desktop because the "Open Anchor App" in the sign in dialogue doesn't work.

They are running Arch Linux, Firefox, KDE Plasma 5.x and using Anchor 1.0.5

**Comment by aaroncox** [comment]
This is most likely due to https://github.com/greymass/anchor/issues/833, where the AppImage isn't working as it should. There's a manual fix in the issue, otherwise installing the deb version should work out of the box. 

Until we get the AppImage fix, we'll probably stop publishing it because this is a pretty common problem people face. 

Going to close this one out and keep #833 open until we get it fixed. Feel free to reopen this issue if the the neither of the above resolve the issue.
