### ISSUE TITLE
Error: import existing account on Jungle 3 Testnet

### ISSUE THREAD

**Issue by abhi3700** [greymass/anchor#956]
I am getting this error while importing an existing account for Jungle 3 Testnet.
Windows OS | [Anchor](url) wallet

![error](https://user-images.githubusercontent.com/16472948/90980384-a4af2780-e578-11ea-8fae-b6d89fd29596.jpg)

Please look into this issue.
Otherwise, it's a great Wallet.
Best part is it is able to show the table data for contract

**Comment by aaroncox** [comment]
This issue is caused by https://github.com/EOSIO/eos/issues/9278, which we're waiting on a fix for. 

In the mean time we just need to keep restarting our API servers in order to pick up new accounts. I just did that, so if you try now, I assume you'll be able to find your account. Let me know if it still doesn't work!
