### ISSUE TITLE
New version 1.1.0 not signed by owner pop-up error encountered during Anchor upgrade

### ISSUE THREAD

**Issue by TrentScott** [greymass/anchor#964]
Just FYI, but you probably already know-- did I try upgrading too soon?  LOL

**Comment by aaroncox** [comment]
Mind sending a screenshot? I'm not sure I know what we're talking about here.

**Comment by TrentScott** [comment]
![image](https://user-images.githubusercontent.com/11326159/92282831-af908300-eebb-11ea-985d-e439d96d9f30.png)

Pop-up appears after download completes...

**Comment by TrentScott** [comment]
I forgot to mention I was upgrading from within the v1.0.5 Windows desktop client.

**Comment by aaroncox** [comment]
Ah interesting, so automatic updates must be broken due to this release changing certificates. That's good to know!

This upgrade might be one where you have to download manually and install: 

https://github.com/greymass/anchor/releases/tag/v1.1.0

We changed the publisher from "Aaron Cox" to "Greymass Inc" in this release with a new certificate. I didn't realize that the automatic updater would actually verify that signature.

**Comment by TrentScott** [comment]
Makes sense-- no worries-- will manually download/install now...

**Comment by aaroncox** [comment]
I do really appreciate the heads up on this, for whatever reason I didn't encounter this issue on my development machine when automatically updating. 

We'll be sure to let everyone know that this upgrade will not work with automatic updates.
